name: Run Telegram Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Stop previous bot
      run: pkill -f bot.py || true

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Remove GitHub Proxy
      run: |
        unset HTTP_PROXY
        unset HTTPS_PROXY
        unset http_proxy
        unset https_proxy
        unset ALL_PROXY
        unset all_proxy

    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        python bot.py &
        sleep infinity
